import type { Metadata } from "next";
import { Inter } from 'next/font/google';

import "./globals.css";
import PizzaCursor from "@/components/PizzaCursor";

export const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});


export const metadata: Metadata = {
  title: "Winner Winner Pizza Dinner",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <PizzaCursor />
        {children}</body>
    </html>
  );
}


