import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import PizzaCursor from "@/components/PizzaCursor";

export const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Winner Winner Pizza Dinner",
  description: "Generated by create next app",
};

import QueryProvider from "@/providers/QueryProvider";
import NextAuthProvider from "@/providers/NextAuthProvider";
import { Toaster } from "sonner";
import Script from "next/script";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable}  h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <Toaster position="bottom-right" richColors />
        <NextAuthProvider>
          <QueryProvider>
            <PizzaCursor />
            {children}
            <Script
              src="https://www.googletagmanager.com/gtag/js?id=G-879LEMJS8V"
              strategy="afterInteractive"
            />

            <Script id="google-analytics" strategy="afterInteractive">
              {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          window.gtag = gtag;
          gtag('js', new Date());
          gtag('config', 'G-879LEMJS8V');
        `}
            </Script>
          </QueryProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
